### POST buat user baru
POST http://localhost:5000/api/register
Content-Type: application/json

{
  "username": "abrar",
  "email": "test2ussdsess2rs22@example.com",
  "password": "abc"
}

###

### login update user
POST https://tpm-tugas-akhir-970101336895.asia-southeast2.run.app/api/login
Content-Type: application/json

{
  "username": "abrar",
  "password": "abc"
}

### GET semua user
GET  https://tpm-tugas-akhir-970101336895.asia-southeast2.run.app/api/users
Content-Type: application/json

###

### GET user by ID
GET http://localhost:5000/api/users/10
Content-Type: application/json

###

### PUT update user
PUT http://localhost:5000/api/users/13`
Content-Type: application/json

{
  "username": "abrar",
  "email": "erickolim@gmail.com",
  "password": "abc",
  "bb": 80,
  "tb": 180,
  "usia": 21,
  "jenis_kelamin": "Laki-laki"
}

###

### DELETE user
DELETE http://localhost:5000/api/users/12
Content-Type: application/json
